DaoCloud/daocloud-api-docs

- source/index.md
> - branch -> ref

- docs/openapi/amamba/v0.16.3.json
- docs/openapi/amamba/v0.16.3.md
openapi: amamba version updated to v0.16.3
> openapi: amamba version updated to v0.16.3

- docs/openapi/amamba/v0.16.2.md
openapi: amamba version updated to v0.16.2
> openapi: amamba version updated to v0.16.2

- docs/openapi/amamba/v0.16.1.md
openapi: amamba version updated to v0.16.1
> openapi: amamba version updated to v0.16.1

- docs/zh/docs/openapi/mcamel/rabbitmq-0.11.0-rc1.json
- docs/zh/docs/openapi/mcamel/rabbitmq-0.11.0-rc1.md
openapi: mcamel rabbitmq version updated to 0.11.0-rc1
> openapi: mcamel rabbitmq version updated to 0.11.0-rc1

- docs/zh/docs/openapi/mcamel/mysql-0.9.0-rc1.json
- docs/zh/docs/openapi/mcamel/mysql-0.9.0-rc1.md
openapi: mcamel mysql version updated to 0.9.0-rc1
> openapi: mcamel mysql version updated to 0.9.0-rc1

- docs/zh/docs/openapi/mcamel/elasticsearch-0.8.0-rc1.json
- docs/zh/docs/openapi/mcamel/elasticsearch-0.8.0-rc1.md
openapi: mcamel elasticsearch version updated to 0.8.0-rc1
> openapi: mcamel elasticsearch version updated to 0.8.0-rc1

- docs/zh/docs/openapi/mcamel/kafka-0.6.0-rc1.json
- docs/zh/docs/openapi/mcamel/kafka-0.6.0-rc1.md
openapi: mcamel kafka version updated to 0.6.0-rc1
> openapi: mcamel kafka version updated to 0.6.0-rc1

- docs/zh/docs/openapi/mcamel/minio-0.6.0-rc1.json
- docs/zh/docs/openapi/mcamel/minio-0.6.0-rc1.md
openapi: mcamel minio version updated to 0.6.0-rc1
> openapi: mcamel minio version updated to 0.6.0-rc1

- docs/zh/docs/openapi/mcamel/postgresql-0.2.0-rc1.json
- docs/zh/docs/openapi/mcamel/postgresql-0.2.0-rc1.md
openapi: mcamel postgresql version updated to 0.2.0-rc1
> openapi: mcamel postgresql version updated to 0.2.0-rc1

- docs/openapi/kangaroo/v0.8.0.md
openapi: kangaroo version updated to v0.8.0
> openapi: kangaroo version updated to v0.8.0

- docs/openapi/spidernet/v0.7.0.json
- docs/openapi/spidernet/v0.7.0.md
openapi: spidernet version updated to v0.7.0
> openapi: spidernet version updated to v0.7.0

- docs/openapi/skoala/v0.22.1.json
- docs/openapi/skoala/v0.22.1.md
openapi: skoala version updated to v0.22.1
> openapi: skoala version updated to v0.22.1

- docs/openapi/ghippo/v0.17.0.json
- docs/openapi/ghippo/v0.17.0.md
openapi: ghippo version updated to v0.17.0
> openapi: ghippo version updated to v0.17.0

- docs/openapi/insight/v0.17.0-rc6.json
- docs/openapi/insight/v0.17.0-rc6.md
openapi: insight version updated to v0.17.0-rc6
> openapi: insight version updated to v0.17.0-rc6

- docs/openapi/amamba/v0.109.1.json
- docs/openapi/amamba/v0.109.1.md
openapi: amamba version updated to v0.109.1
> openapi: amamba version updated to v0.109.1

- docs/openapi/mcamel/kafka-v0.6.0.json
- docs/openapi/mcamel/kafka-v0.6.0.md
openapi: mcamel kafka version updated to v0.6.0
> openapi: mcamel kafka version updated to v0.6.0

- docs/openapi/mcamel/elasticsearch-v0.8.0.json
- docs/openapi/mcamel/elasticsearch-v0.8.0.md
openapi: mcamel elasticsearch version updated to v0.8.0
> openapi: mcamel elasticsearch version updated to v0.8.0

- docs/openapi/mcamel/redis-v0.8.0.json
- docs/openapi/mcamel/redis-v0.8.0.md
openapi: mcamel redis version updated to v0.8.0
> openapi: mcamel redis version updated to v0.8.0

- docs/openapi/mcamel/postgresql-v0.2.0.json
- docs/openapi/mcamel/postgresql-v0.2.0.md
openapi: mcamel postgresql version updated to v0.2.0
> openapi: mcamel postgresql version updated to v0.2.0

- docs/openapi/mcamel/mysql-v0.9.0.json
- docs/openapi/mcamel/mysql-v0.9.0.md
openapi: mcamel mysql version updated to v0.9.0
> openapi: mcamel mysql version updated to v0.9.0

- docs/openapi/mcamel/rabbitmq-v0.11.0.json
- docs/openapi/mcamel/rabbitmq-v0.11.0.md
openapi: mcamel rabbitmq version updated to v0.11.0
> openapi: mcamel rabbitmq version updated to v0.11.0

- docs/openapi/mcamel/minio-v0.6.0.json
- docs/openapi/mcamel/minio-v0.6.0.md
openapi: mcamel minio version updated to v0.6.0
> openapi: mcamel minio version updated to v0.6.0

- docs/openapi/insight/v0.17.1.json
- docs/openapi/insight/v0.17.1.md
openapi: insight version updated to v0.17.1
> openapi: insight version updated to v0.17.1

- docs/openapi/insight/v0.17.2.json
- docs/openapi/insight/v0.17.2.md
openapi: insight version updated to v0.17.2
> openapi: insight version updated to v0.17.2

- docs/openapi/kairship/v0.9.0.json
- docs/openapi/kairship/v0.9.0.md
openapi: kairship version updated to v0.9.0
> openapi: kairship version updated to v0.9.0

- docs/openapi/ghippo/v0.17.1.json
- docs/openapi/ghippo/v0.17.1.md
openapi: ghippo version updated to v0.17.1
> openapi: ghippo version updated to v0.17.1

- docs/openapi/insight/v0.17.3.json
- docs/openapi/insight/v0.17.3.md
openapi: insight version updated to v0.17.3
> openapi: insight version updated to v0.17.3

- docs/openapi/spidernet/v0.8.0.json
- docs/openapi/spidernet/v0.8.0.md
openapi: spidernet version updated to v0.8.0
> openapi: spidernet version updated to v0.8.0

- docs/openapi/amamba/v0.110.0.json
- docs/openapi/amamba/v0.110.0.md
openapi: amamba version updated to v0.110.0
> openapi: amamba version updated to v0.110.0

- docs/openapi/kairship/v0.10.0.json
- docs/openapi/kairship/v0.10.0.md
openapi: kairship version updated to v0.10.0
> openapi: kairship version updated to v0.10.0

- docs/openapi/skoala/v0.23.0.json
- docs/openapi/skoala/v0.23.0.md
openapi: skoala version updated to v0.23.0
> openapi: skoala version updated to v0.23.0

- docs/openapi/ghippo/v0.18.0.json
- docs/openapi/ghippo/v0.18.0.md
openapi: ghippo version updated to v0.18.0
> openapi: ghippo version updated to v0.18.0

- docs/openapi/kairship/v0.10.1.json
- docs/openapi/kairship/v0.10.1.md
openapi: kairship version updated to v0.10.1
> openapi: kairship version updated to v0.10.1

- docs/openapi/kairship/v0.10.2.json
- docs/openapi/kairship/v0.10.2.md
openapi: kairship version updated to v0.10.2
> openapi: kairship version updated to v0.10.2

- docs/openapi/mcamel/mysql-v0.10.0.json
- docs/openapi/mcamel/mysql-v0.10.0.md
openapi: mcamel mysql version updated to v0.10.0
> openapi: mcamel mysql version updated to v0.10.0

- docs/openapi/mcamel/postgresql-v0.3.0.json
- docs/openapi/mcamel/postgresql-v0.3.0.md
openapi: mcamel postgresql version updated to v0.3.0
> openapi: mcamel postgresql version updated to v0.3.0

- docs/openapi/mcamel/minio-v0.7.0.json
- docs/openapi/mcamel/minio-v0.7.0.md
openapi: mcamel minio version updated to v0.7.0
> openapi: mcamel minio version updated to v0.7.0

- docs/openapi/mcamel/rabbitmq-v0.12.0.json
- docs/openapi/mcamel/rabbitmq-v0.12.0.md
openapi: mcamel rabbitmq version updated to v0.12.0
> openapi: mcamel rabbitmq version updated to v0.12.0

- docs/openapi/mcamel/kafka-v0.7.0.json
- docs/openapi/mcamel/kafka-v0.7.0.md
openapi: mcamel kafka version updated to v0.7.0
> openapi: mcamel kafka version updated to v0.7.0

- docs/openapi/mcamel/elasticsearch-v0.9.0.json
- docs/openapi/mcamel/elasticsearch-v0.9.0.md
openapi: mcamel elasticsearch version updated to v0.9.0
> openapi: mcamel elasticsearch version updated to v0.9.0

- docs/openapi/mcamel/redis-v0.9.0.json
- docs/openapi/mcamel/redis-v0.9.0.md
openapi: mcamel redis version updated to v0.9.0
> openapi: mcamel redis version updated to v0.9.0

- docs/openapi/mcamel/mongodb-v0.1.0.json
- docs/openapi/mcamel/mongodb-v0.1.0.md
openapi: mcamel mongodb version updated to v0.1.0
> openapi: mcamel mongodb version updated to v0.1.0

- docs/openapi/kairship/v0.10.3.json
- docs/openapi/kairship/v0.10.3.md
openapi: kairship version updated to v0.10.3
> openapi: kairship version updated to v0.10.3

- docs/openapi/skoala/v0.24.0.json
- docs/openapi/skoala/v0.24.0.md
openapi: skoala version updated to v0.24.0
> openapi: skoala version updated to v0.24.0

- docs/openapi/kangaroo/v0.9.1.json
- docs/openapi/kangaroo/v0.9.1.md
openapi: kangaroo version updated to v0.9.1
> openapi: kangaroo version updated to v0.9.1

- docs/openapi/insight/v0.18.0.json
- docs/openapi/insight/v0.18.0.md
openapi: insight version updated to v0.18.0
> openapi: insight version updated to v0.18.0

- docs/openapi/insight/v0.18.1.json
- docs/openapi/insight/v0.18.1.md
openapi: insight version updated to v0.18.1
> openapi: insight version updated to v0.18.1

- docs/openapi/insight/v0.18.2.json
- docs/openapi/insight/v0.18.2.md
openapi: insight version updated to v0.18.2
> openapi: insight version updated to v0.18.2

- docs/openapi/skoala/v0.24.1.json
- docs/openapi/skoala/v0.24.1.md
openapi: skoala version updated to v0.24.1
> openapi: skoala version updated to v0.24.1

- docs/openapi/skoala/v0.24.2.json
- docs/openapi/skoala/v0.24.2.md
openapi: skoala version updated to v0.24.2
> openapi: skoala version updated to v0.24.2

- docs/openapi/ghippo/v0.18.1.json
- docs/openapi/ghippo/v0.18.1.md
openapi: ghippo version updated to v0.18.1
> openapi: ghippo version updated to v0.18.1

- docs/openapi/skoala/v0.25.0.json
- docs/openapi/skoala/v0.25.0.md
openapi: skoala version updated to v0.25.0
> openapi: skoala version updated to v0.25.0

- docs/openapi/mcamel/rabbitmq-v0.12.1.json
- docs/openapi/mcamel/rabbitmq-v0.12.1.md
openapi: mcamel rabbitmq version updated to v0.12.1
> openapi: mcamel rabbitmq version updated to v0.12.1

- docs/openapi/mcamel/mysql-v0.10.1.json
- docs/openapi/mcamel/mysql-v0.10.1.md
openapi: mcamel mysql version updated to v0.10.1
> openapi: mcamel mysql version updated to v0.10.1

- docs/openapi/amamba/v0.111.0.json
- docs/openapi/amamba/v0.111.0.md
openapi: amamba version updated to v0.111.0
> openapi: amamba version updated to v0.111.0

- docs/openapi/mcamel/kafka-v0.7.1.json
- docs/openapi/mcamel/kafka-v0.7.1.md
openapi: mcamel kafka version updated to v0.7.1
> openapi: mcamel kafka version updated to v0.7.1

- docs/openapi/mcamel/minio-v0.7.1.json
- docs/openapi/mcamel/minio-v0.7.1.md
openapi: mcamel minio version updated to v0.7.1
> openapi: mcamel minio version updated to v0.7.1

- docs/openapi/skoala/v0.26.1.json
- docs/openapi/skoala/v0.26.1.md
openapi: skoala version updated to v0.26.1
> openapi: skoala version updated to v0.26.1

- docs/openapi/skoala/v0.26.0.json
- docs/openapi/skoala/v0.26.0.md
openapi: skoala version updated to v0.26.0
> openapi: skoala version updated to v0.26.0

- docs/openapi/spidernet/v0.8.1.json
- docs/openapi/spidernet/v0.8.1.md
openapi: spidernet version updated to v0.8.1
> openapi: spidernet version updated to v0.8.1

- docs/openapi/kangaroo/v0.10.0.json
- docs/openapi/kangaroo/v0.10.0.md
openapi: kangaroo version updated to v0.10.0
> openapi: kangaroo version updated to v0.10.0

- docs/openapi/mcamel/rabbitmq-v0.12.2.json
- docs/openapi/mcamel/rabbitmq-v0.12.2.md
openapi: mcamel rabbitmq version updated to v0.12.2
> openapi: mcamel rabbitmq version updated to v0.12.2

- docs/openapi/mcamel/kafka-v0.7.2.json
- docs/openapi/mcamel/kafka-v0.7.2.md
openapi: mcamel kafka version updated to v0.7.2
> openapi: mcamel kafka version updated to v0.7.2

- docs/openapi/mcamel/minio-v0.7.2.json
- docs/openapi/mcamel/minio-v0.7.2.md
openapi: mcamel minio version updated to v0.7.2
> openapi: mcamel minio version updated to v0.7.2

- docs/openapi/mcamel/mysql-v0.10.2.json
- docs/openapi/mcamel/mysql-v0.10.2.md
openapi: mcamel mysql version updated to v0.10.2
> openapi: mcamel mysql version updated to v0.10.2

- docs/openapi/mcamel/elasticsearch-v0.9.2.json
- docs/openapi/mcamel/elasticsearch-v0.9.2.md
openapi: mcamel elasticsearch version updated to v0.9.2
> openapi: mcamel elasticsearch version updated to v0.9.2

- docs/openapi/ghippo/v0.19.0.json
- docs/openapi/ghippo/v0.19.0.md
openapi: ghippo version updated to v0.19.0
> openapi: ghippo version updated to v0.19.0

- docs/openapi/mcamel/kafka-v0.7.3.json
- docs/openapi/mcamel/kafka-v0.7.3.md
openapi: mcamel kafka version updated to v0.7.3
> openapi: mcamel kafka version updated to v0.7.3

- docs/openapi/mcamel/redis-v0.10.0.json
- docs/openapi/mcamel/redis-v0.10.0.md
openapi: mcamel redis version updated to v0.10.0
> openapi: mcamel redis version updated to v0.10.0

- docs/openapi/kairship/v0.11.0.json
- docs/openapi/kairship/v0.11.0.md
openapi: kairship version updated to v0.11.0
> openapi: kairship version updated to v0.11.0

- docs/openapi/mcamel/mysql-v0.10.3.json
- docs/openapi/mcamel/mysql-v0.10.3.md
openapi: mcamel mysql version updated to v0.10.3
> openapi: mcamel mysql version updated to v0.10.3

- docs/openapi/mcamel/minio-v0.7.3.json
- docs/openapi/mcamel/minio-v0.7.3.md
openapi: mcamel minio version updated to v0.7.3
> openapi: mcamel minio version updated to v0.7.3

- docs/openapi/mcamel/postgresql-v0.4.0.json
- docs/openapi/mcamel/postgresql-v0.4.0.md
openapi: mcamel postgresql version updated to v0.4.0
> openapi: mcamel postgresql version updated to v0.4.0

- docs/openapi/mcamel/mongodb-v0.2.0.json
- docs/openapi/mcamel/mongodb-v0.2.0.md
openapi: mcamel mongodb version updated to v0.2.0
> openapi: mcamel mongodb version updated to v0.2.0

- docs/openapi/mcamel/elasticsearch-v0.9.3.json
- docs/openapi/mcamel/elasticsearch-v0.9.3.md
openapi: mcamel elasticsearch version updated to v0.9.3
> openapi: mcamel elasticsearch version updated to v0.9.3

- docs/openapi/mcamel/rabbitmq-v0.12.3.json
- docs/openapi/mcamel/rabbitmq-v0.12.3.md
openapi: mcamel rabbitmq version updated to v0.12.3
> openapi: mcamel rabbitmq version updated to v0.12.3

- docs/openapi/insight/v0.19.1.json
- docs/openapi/insight/v0.19.1.md
openapi: insight version updated to v0.19.1
> openapi: insight version updated to v0.19.1

- docs/openapi/kangaroo/v0.10.1.json
- docs/openapi/kangaroo/v0.10.1.md
openapi: kangaroo version updated to v0.10.1
> openapi: kangaroo version updated to v0.10.1

- docs/openapi/insight/v0.19.0.json
- docs/openapi/insight/v0.19.0.md
openapi: insight version updated to v0.19.0
> openapi: insight version updated to v0.19.0

- docs/openapi/skoala/v0.26.2.json
- docs/openapi/skoala/v0.26.2.md
openapi: skoala version updated to v0.26.2
> openapi: skoala version updated to v0.26.2

- docs/openapi/kairship/v0.11.1.json
- docs/openapi/kairship/v0.11.1.md
openapi: kairship version updated to v0.11.1
> openapi: kairship version updated to v0.11.1

- docs/openapi/insight/v0.19.2.json
- docs/openapi/insight/v0.19.2.md
openapi: insight version updated to v0.19.2
> openapi: insight version updated to v0.19.2

- docs/openapi/amamba/v0.112.0.json
- docs/openapi/amamba/v0.112.0.md
openapi: amamba version updated to v0.112.0
> openapi: amamba version updated to v0.112.0

- docs/openapi/amamba/v0.111.2.json
- docs/openapi/amamba/v0.111.2.md
openapi: amamba version updated to v0.111.2
> openapi: amamba version updated to v0.111.2

- docs/openapi/skoala/v0.27.0.json
- docs/openapi/skoala/v0.27.0.md
openapi: skoala version updated to v0.27.0
> openapi: skoala version updated to v0.27.0

- docs/openapi/spidernet/v0.9.0.json
- docs/openapi/spidernet/v0.9.0.md
openapi: spidernet version updated to v0.9.0
> openapi: spidernet version updated to v0.9.0

- docs/openapi/ghippo/v0.20.0.json
- docs/openapi/ghippo/v0.20.0.md
openapi: ghippo version updated to v0.20.0
> openapi: ghippo version updated to v0.20.0

- docs/openapi/skoala/v0.27.1.json
- docs/openapi/skoala/v0.27.1.md
openapi: skoala version updated to v0.27.1
> openapi: skoala version updated to v0.27.1

- docs/openapi/kairship/v0.12.0.json
- docs/openapi/kairship/v0.12.0.md
openapi: kairship version updated to v0.12.0
> openapi: kairship version updated to v0.12.0

- docs/openapi/skoala/v0.27.2.json
- docs/openapi/skoala/v0.27.2.md
openapi: skoala version updated to v0.27.2
> openapi: skoala version updated to v0.27.2

- docs/openapi/mcamel/mongodb/mongodb-v0.3.0.json
- docs/openapi/mcamel/mongodb/mongodb-v0.3.0.md
openapi: mcamel mongodb version updated to v0.3.0
> openapi: mcamel mongodb version updated to v0.3.0

- docs/openapi/mcamel/postgresql/postgresql-v0.5.0.json
- docs/openapi/mcamel/postgresql/postgresql-v0.5.0.md
openapi: mcamel postgresql version updated to v0.5.0
> openapi: mcamel postgresql version updated to v0.5.0

- docs/openapi/mcamel/minio/minio-v0.8.0.json
- docs/openapi/mcamel/minio/minio-v0.8.0.md
openapi: mcamel minio version updated to v0.8.0
> openapi: mcamel minio version updated to v0.8.0

- docs/openapi/mcamel/mysql/mysql-v0.11.0.json
- docs/openapi/mcamel/mysql/mysql-v0.11.0.md
openapi: mcamel mysql version updated to v0.11.0
> openapi: mcamel mysql version updated to v0.11.0

- docs/openapi/mcamel/elasticsearch/elasticsearch-v0.10.0.json
- docs/openapi/mcamel/elasticsearch/elasticsearch-v0.10.0.md
openapi: mcamel elasticsearch version updated to v0.10.0
> openapi: mcamel elasticsearch version updated to v0.10.0

- docs/openapi/mcamel/rabbitmq/rabbitmq-v0.13.0.json
- docs/openapi/mcamel/rabbitmq/rabbitmq-v0.13.0.md
openapi: mcamel rabbitmq version updated to v0.13.0
> openapi: mcamel rabbitmq version updated to v0.13.0

- docs/openapi/mcamel/redis/redis-v0.11.0.json
- docs/openapi/mcamel/redis/redis-v0.11.0.md
openapi: mcamel redis version updated to v0.11.0
> openapi: mcamel redis version updated to v0.11.0

- docs/openapi/insight/v0.20.0.json
- docs/openapi/insight/v0.20.0.md
openapi: insight version updated to v0.20.0
> openapi: insight version updated to v0.20.0

- docs/openapi/mcamel/kafka/kafka-v0.8.0.json
- docs/openapi/mcamel/kafka/kafka-v0.8.0.md
openapi: mcamel kafka version updated to v0.8.0
> openapi: mcamel kafka version updated to v0.8.0

- docs/openapi/ghippo/v0.20.1.json
- docs/openapi/ghippo/v0.20.1.md
openapi: ghippo version updated to v0.20.1
> openapi: ghippo version updated to v0.20.1

- docs/openapi/kangaroo/v0.11.0.json
- docs/openapi/kangaroo/v0.11.0.md
openapi: kangaroo version updated to v0.11.0
> openapi: kangaroo version updated to v0.11.0

- docs/openapi/mcamel/rabbitmq/rabbitmq-v0.13.1.json
- docs/openapi/mcamel/rabbitmq/rabbitmq-v0.13.1.md
openapi: mcamel rabbitmq version updated to v0.13.1
> openapi: mcamel rabbitmq version updated to v0.13.1

- docs/openapi/mcamel/mysql/mysql-v0.11.1.json
- docs/openapi/mcamel/mysql/mysql-v0.11.1.md
openapi: mcamel mysql version updated to v0.11.1
> openapi: mcamel mysql version updated to v0.11.1

- docs/openapi/mcamel/postgresql/postgresql-v0.5.1.json
- docs/openapi/mcamel/postgresql/postgresql-v0.5.1.md
openapi: mcamel postgresql version updated to v0.5.1
> openapi: mcamel postgresql version updated to v0.5.1

- docs/openapi/mcamel/minio/minio-v0.8.1.json
- docs/openapi/mcamel/minio/minio-v0.8.1.md
openapi: mcamel minio version updated to v0.8.1
> openapi: mcamel minio version updated to v0.8.1

- docs/openapi/mcamel/mongodb/mongodb-v0.3.1.json
- docs/openapi/mcamel/mongodb/mongodb-v0.3.1.md
openapi: mcamel mongodb version updated to v0.3.1
> openapi: mcamel mongodb version updated to v0.3.1

- docs/openapi/mcamel/elasticsearch/elasticsearch-v0.10.1.json
- docs/openapi/mcamel/elasticsearch/elasticsearch-v0.10.1.md
openapi: mcamel elasticsearch version updated to v0.10.1
> openapi: mcamel elasticsearch version updated to v0.10.1

- docs/openapi/mcamel/redis/redis-v0.11.1.json
- docs/openapi/mcamel/redis/redis-v0.11.1.md
openapi: mcamel redis version updated to v0.11.1
> openapi: mcamel redis version updated to v0.11.1

- docs/openapi/index.md
- docs/openapi/midware.md
- openapi-nav.yml
- 按文档顺序调整 openapi
- 补充缺少的 nav 和 index
> update openapi nav and index

- docs/openapi/kairship/v0.13.0.json
- docs/openapi/kairship/v0.13.0.md
openapi: kairship version updated to v0.13.0
> openapi: kairship version updated to v0.13.0

- docs/openapi/spidernet/v0.10.0.json
- docs/openapi/spidernet/v0.10.0.md
openapi: spidernet version updated to v0.10.0
> openapi: spidernet version updated to v0.10.0

- docs/openapi/skoala/v0.28.0.json
- docs/openapi/skoala/v0.28.0.md
openapi: skoala version updated to v0.28.0
> openapi: skoala version updated to v0.28.0

- docs/openapi/kangaroo/v0.12.0.json
- docs/openapi/kangaroo/v0.12.0.md
openapi: kangaroo version updated to v0.12.0
> openapi: kangaroo version updated to v0.12.0

- docs/openapi/spidernet/v0.10.1.json
- docs/openapi/spidernet/v0.10.1.md
openapi: spidernet version updated to v0.10.1
> openapi: spidernet version updated to v0.10.1

- docs/openapi/skoala/v0.28.1.json
- docs/openapi/skoala/v0.28.1.md
openapi: skoala version updated to v0.28.1
> openapi: skoala version updated to v0.28.1

- docs/openapi/insight/v0.21.1.json
- docs/openapi/insight/v0.21.1.md
openapi: insight version updated to v0.21.1
> openapi: insight version updated to v0.21.1

- docs/openapi/kangaroo/v0.12.1.json
- docs/openapi/kangaroo/v0.12.1.md
openapi: kangaroo version updated to v0.12.1
> openapi: kangaroo version updated to v0.12.1

- docs/openapi/kairship/v0.13.1.json
- docs/openapi/kairship/v0.13.1.md
openapi: kairship version updated to v0.13.1
> openapi: kairship version updated to v0.13.1

- docs/openapi/mcamel/rocketmq-v0.1.1.json
- docs/openapi/mcamel/rocketmq-v0.1.1.md
openapi: mcamel rocketmq version updated to v0.1.1
> openapi: mcamel rocketmq version updated to v0.1.1

- docs/openapi/mcamel/kafka/kafka-v0.9.0.json
- docs/openapi/mcamel/kafka/kafka-v0.9.0.md
openapi: mcamel kafka version updated to v0.9.0
> openapi: mcamel kafka version updated to v0.9.0

- docs/openapi/mcamel/elasticsearch/elasticsearch-v0.11.0.json
- docs/openapi/mcamel/elasticsearch/elasticsearch-v0.11.0.md
openapi: mcamel elasticsearch version updated to v0.11.0
> openapi: mcamel elasticsearch version updated to v0.11.0

- docs/openapi/mcamel/minio/minio-v0.9.0.json
- docs/openapi/mcamel/minio/minio-v0.9.0.md
openapi: mcamel minio version updated to v0.9.0
> openapi: mcamel minio version updated to v0.9.0

- docs/openapi/mcamel/postgresql/postgresql-v0.6.0.json
- docs/openapi/mcamel/postgresql/postgresql-v0.6.0.md
openapi: mcamel postgresql version updated to v0.6.0
> openapi: mcamel postgresql version updated to v0.6.0

- docs/openapi/mcamel/rabbitmq/rabbitmq-v0.14.0.json
- docs/openapi/mcamel/rabbitmq/rabbitmq-v0.14.0.md
openapi: mcamel rabbitmq version updated to v0.14.0
> openapi: mcamel rabbitmq version updated to v0.14.0

- docs/openapi/mcamel/mysql/mysql-v0.12.0.json
- docs/openapi/mcamel/mysql/mysql-v0.12.0.md
openapi: mcamel mysql version updated to v0.12.0
> openapi: mcamel mysql version updated to v0.12.0

- docs/openapi/mcamel/mongodb/mongodb-v0.4.0.json
- docs/openapi/mcamel/mongodb/mongodb-v0.4.0.md
openapi: mcamel mongodb version updated to v0.4.0
> openapi: mcamel mongodb version updated to v0.4.0

- docs/openapi/ghippo/v0.21.0.json
- docs/openapi/ghippo/v0.21.0.md
openapi: ghippo version updated to v0.21.0
> openapi: ghippo version updated to v0.21.0

- docs/openapi/kangaroo/v0.13.0.json
- docs/openapi/kangaroo/v0.13.0.md
openapi: kangaroo version updated to v0.13.0
> openapi: kangaroo version updated to v0.13.0

- docs/openapi/insight/v0.21.2.json
- docs/openapi/insight/v0.21.2.md
openapi: insight version updated to v0.21.2
> openapi: insight version updated to v0.21.2

- docs/openapi/insight/v0.21.0.json
- docs/openapi/insight/v0.21.0.md
openapi: insight version updated to v0.21.0
> openapi: insight version updated to v0.21.0

- docs/openapi/kairship/v0.14.0.json
- docs/openapi/kairship/v0.14.0.md
openapi: kairship version updated to v0.14.0
> openapi: kairship version updated to v0.14.0

- docs/openapi/skoala/v0.30.0.json
- docs/openapi/skoala/v0.30.0.md
openapi: skoala version updated to v0.30.0
> openapi: skoala version updated to v0.30.0

- docs/openapi/kangaroo/v0.13.1.json
- docs/openapi/kangaroo/v0.13.1.md
openapi: kangaroo version updated to v0.13.1
> openapi: kangaroo version updated to v0.13.1

- docs/openapi/mcamel/rocketmq-v0.2.0.json
- docs/openapi/mcamel/rocketmq-v0.2.0.md
openapi: mcamel rocketmq version updated to v0.2.0
> openapi: mcamel rocketmq version updated to v0.2.0

- docs/openapi/mcamel/mongodb/mongodb-v0.5.0.json
- docs/openapi/mcamel/mongodb/mongodb-v0.5.0.md
openapi: mcamel mongodb version updated to v0.5.0
> openapi: mcamel mongodb version updated to v0.5.0

- docs/openapi/mcamel/minio/minio-v0.10.0.json
- docs/openapi/mcamel/minio/minio-v0.10.0.md
openapi: mcamel minio version updated to v0.10.0
> openapi: mcamel minio version updated to v0.10.0

- docs/openapi/mcamel/postgresql/postgresql-v0.7.0.json
- docs/openapi/mcamel/postgresql/postgresql-v0.7.0.md
openapi: mcamel postgresql version updated to v0.7.0
> openapi: mcamel postgresql version updated to v0.7.0

- docs/openapi/mcamel/redis/redis-v0.13.0.json
- docs/openapi/mcamel/redis/redis-v0.13.0.md
openapi: mcamel redis version updated to v0.13.0
> openapi: mcamel redis version updated to v0.13.0

- docs/openapi/mcamel/rabbitmq/rabbitmq-v0.15.0.json
- docs/openapi/mcamel/rabbitmq/rabbitmq-v0.15.0.md
openapi: mcamel rabbitmq version updated to v0.15.0
> openapi: mcamel rabbitmq version updated to v0.15.0

- docs/openapi/mcamel/elasticsearch/elasticsearch-v0.12.0.json
- docs/openapi/mcamel/elasticsearch/elasticsearch-v0.12.0.md
openapi: mcamel elasticsearch version updated to v0.12.0
> openapi: mcamel elasticsearch version updated to v0.12.0

- docs/openapi/ghippo/v0.22.1.json
- docs/openapi/ghippo/v0.22.1.md
openapi: ghippo version updated to v0.22.1
> openapi: ghippo version updated to v0.22.1

- docs/openapi/insight/v0.22.0.json
- docs/openapi/insight/v0.22.0.md
openapi: insight version updated to v0.22.0
> openapi: insight version updated to v0.22.0

- docs/openapi/insight/v0.22.1.json
- docs/openapi/insight/v0.22.1.md
openapi: insight version updated to v0.22.1
> openapi: insight version updated to v0.22.1

- docs/openapi/spidernet/v0.12.0.json
- docs/openapi/spidernet/v0.12.0.md
openapi: spidernet version updated to v0.12.0
> openapi: spidernet version updated to v0.12.0

- docs/openapi/kangaroo/v0.14.0.json
- docs/openapi/kangaroo/v0.14.0.md
openapi: kangaroo version updated to v0.14.0
> openapi: kangaroo version updated to v0.14.0

- docs/openapi/ghippo/v0.23.0.json
- docs/openapi/ghippo/v0.23.0.md
openapi: ghippo version updated to v0.23.0
> openapi: ghippo version updated to v0.23.0

- docs/openapi/kairship/v0.15.0.json
- docs/openapi/kairship/v0.15.0.md
openapi: kairship version updated to v0.15.0
> openapi: kairship version updated to v0.15.0

- docs/openapi/spidernet/v0.12.1.json
- docs/openapi/spidernet/v0.12.1.md
openapi: spidernet version updated to v0.12.1
> openapi: spidernet version updated to v0.12.1

- docs/openapi/mcamel/rabbitmq/rabbitmq-v0.16.0.json
- docs/openapi/mcamel/rabbitmq/rabbitmq-v0.16.0.md
openapi: mcamel rabbitmq version updated to v0.16.0
> openapi: mcamel rabbitmq version updated to v0.16.0

- docs/openapi/mcamel/elasticsearch/elasticsearch-v0.13.0.json
- docs/openapi/mcamel/elasticsearch/elasticsearch-v0.13.0.md
openapi: mcamel elasticsearch version updated to v0.13.0
> openapi: mcamel elasticsearch version updated to v0.13.0

- docs/openapi/mcamel/rocketmq-v0.3.0.json
- docs/openapi/mcamel/rocketmq-v0.3.0.md
openapi: mcamel rocketmq version updated to v0.3.0
> openapi: mcamel rocketmq version updated to v0.3.0

- docs/openapi/mcamel/mongodb/mongodb-v0.6.0.json
- docs/openapi/mcamel/mongodb/mongodb-v0.6.0.md
openapi: mcamel mongodb version updated to v0.6.0
> openapi: mcamel mongodb version updated to v0.6.0

- docs/openapi/mcamel/kafka/kafka-v0.11.0.json
- docs/openapi/mcamel/kafka/kafka-v0.11.0.md
openapi: mcamel kafka version updated to v0.11.0
> openapi: mcamel kafka version updated to v0.11.0

- docs/openapi/mcamel/redis/redis-v0.14.0.json
- docs/openapi/mcamel/redis/redis-v0.14.0.md
openapi: mcamel redis version updated to v0.14.0
> openapi: mcamel redis version updated to v0.14.0

- docs/openapi/mcamel/postgresql/postgresql-v0.8.0.json
- docs/openapi/mcamel/postgresql/postgresql-v0.8.0.md
openapi: mcamel postgresql version updated to v0.8.0
> openapi: mcamel postgresql version updated to v0.8.0

- docs/openapi/mcamel/mysql/mysql-v0.14.0.json
- docs/openapi/mcamel/mysql/mysql-v0.14.0.md
openapi: mcamel mysql version updated to v0.14.0
> openapi: mcamel mysql version updated to v0.14.0

- docs/openapi/mcamel/minio/minio-v0.11.0.json
- docs/openapi/mcamel/minio/minio-v0.11.0.md
openapi: mcamel minio version updated to v0.11.0
> openapi: mcamel minio version updated to v0.11.0

- docs/openapi/mcamel/kafka/kafka-v0.11.1.json
- docs/openapi/mcamel/kafka/kafka-v0.11.1.md
openapi: mcamel kafka version updated to v0.11.1
> openapi: mcamel kafka version updated to v0.11.1

- docs/openapi/mcamel/kafka/kafka-v0.11.2.json
- docs/openapi/mcamel/kafka/kafka-v0.11.2.md
openapi: mcamel kafka version updated to v0.11.2
> openapi: mcamel kafka version updated to v0.11.2

- docs/openapi/skoala/v0.31.2.json
- docs/openapi/skoala/v0.31.2.md
openapi: skoala version updated to v0.31.2
> openapi: skoala version updated to v0.31.2

- docs/openapi/ghippo/v0.23.1.json
- docs/openapi/ghippo/v0.23.1.md
openapi: ghippo version updated to v0.23.1
> openapi: ghippo version updated to v0.23.1

- docs/openapi/skoala/v0.32.0.json
- docs/openapi/skoala/v0.32.0.md
openapi: skoala version updated to v0.32.0
> openapi: skoala version updated to v0.32.0

- docs/openapi/kairship/v0.16.0.json
- docs/openapi/kairship/v0.16.0.md
openapi: kairship version updated to v0.16.0
> openapi: kairship version updated to v0.16.0

- docs/openapi/spidernet/v0.13.0.json
- docs/openapi/spidernet/v0.13.0.md
openapi: spidernet version updated to v0.13.0
> openapi: spidernet version updated to v0.13.0

- docs/openapi/kangaroo/v0.15.0.json
- docs/openapi/kangaroo/v0.15.0.md
openapi: kangaroo version updated to v0.15.0
> openapi: kangaroo version updated to v0.15.0

- docs/openapi/kant/v0.8.0.json
- docs/openapi/kant/v0.8.0.md
> Add kant openapi

- docs/openapi/skoala/v0.33.1.json
- docs/openapi/skoala/v0.33.1.md
openapi: skoala version updated to v0.33.1
> openapi: skoala version updated to v0.33.1

- docs/openapi/insight/v0.23.1.json
- docs/openapi/insight/v0.23.1.md
openapi: insight version updated to v0.23.1
> openapi: insight version updated to v0.23.1

- docs/openapi/mcamel/mongodb/mongodb-v0.7.0.json
- docs/openapi/mcamel/mongodb/mongodb-v0.7.0.md
openapi: mcamel mongodb version updated to v0.7.0
> openapi: mcamel mongodb version updated to v0.7.0

- docs/openapi/mcamel/redis/redis-v0.15.0.json
- docs/openapi/mcamel/redis/redis-v0.15.0.md
openapi: mcamel redis version updated to v0.15.0
> openapi: mcamel redis version updated to v0.15.0

- docs/openapi/mcamel/postgresql/postgresql-v0.9.0.json
- docs/openapi/mcamel/postgresql/postgresql-v0.9.0.md
openapi: mcamel postgresql version updated to v0.9.0
> openapi: mcamel postgresql version updated to v0.9.0

- docs/openapi/mcamel/mysql/mysql-v0.15.0.json
- docs/openapi/mcamel/mysql/mysql-v0.15.0.md
openapi: mcamel mysql version updated to v0.15.0
> openapi: mcamel mysql version updated to v0.15.0

- docs/openapi/mcamel/minio/minio-v0.12.0.json
- docs/openapi/mcamel/minio/minio-v0.12.0.md
openapi: mcamel minio version updated to v0.12.0
> openapi: mcamel minio version updated to v0.12.0

- docs/openapi/mcamel/rocketmq-v0.4.0.json
- docs/openapi/mcamel/rocketmq-v0.4.0.md
openapi: mcamel rocketmq version updated to v0.4.0
> openapi: mcamel rocketmq version updated to v0.4.0

- docs/openapi/mcamel/rabbitmq/rabbitmq-v0.17.0.json
- docs/openapi/mcamel/rabbitmq/rabbitmq-v0.17.0.md
openapi: mcamel rabbitmq version updated to v0.17.0
> openapi: mcamel rabbitmq version updated to v0.17.0

- docs/openapi/mcamel/kafka/kafka-v0.12.0.json
- docs/openapi/mcamel/kafka/kafka-v0.12.0.md
openapi: mcamel kafka version updated to v0.12.0
> openapi: mcamel kafka version updated to v0.12.0

- docs/openapi/ghippo/v0.24.0.json
- docs/openapi/ghippo/v0.24.0.md
openapi: ghippo version updated to v0.24.0
> openapi: ghippo version updated to v0.24.0

- docs/openapi/skoala/v0.33.2.json
- docs/openapi/skoala/v0.33.2.md
openapi: skoala version updated to v0.33.2
> openapi: skoala version updated to v0.33.2

- docs/openapi/skoala/v0.34.0.json
- docs/openapi/skoala/v0.34.0.md
openapi: skoala version updated to v0.34.0
> openapi: skoala version updated to v0.34.0

- docs/openapi/insight/v0.24.0.json
- docs/openapi/insight/v0.24.0.md
openapi: insight version updated to v0.24.0
> openapi: insight version updated to v0.24.0

- docs/openapi/skoala/v0.33.3.json
- docs/openapi/skoala/v0.33.3.md
openapi: skoala version updated to v0.33.3
> openapi: skoala version updated to v0.33.3

- openapi-nav.yml
> update openapi nav

- docs/openapi/virtnest/v0.6.0.json
- docs/openapi/virtnest/v0.6.0.md
openapi: virtnest version updated to v0.6.0
> openapi: virtnest version updated to v0.6.0

- docs/openapi/index.md
> add virtnest index

- openapi-nav.yml
>  add virtnest nav

- docs/openapi/ghippo/v0.24.1.json
- docs/openapi/ghippo/v0.24.1.md
openapi: ghippo version updated to v0.24.1
> openapi: ghippo version updated to v0.24.1

- docs/openapi/kairship/v0.17.0.json
- docs/openapi/kairship/v0.17.0.md
openapi: kairship version updated to v0.17.0
> openapi: kairship version updated to v0.17.0

- docs/openapi/skoala/v0.35.0.json
- docs/openapi/skoala/v0.35.0.md
openapi: skoala version updated to v0.35.0
> openapi: skoala version updated to v0.35.0

- docs/openapi/virtnest/v0.7.0.json
- docs/openapi/virtnest/v0.7.0.md
openapi: virtnest version updated to v0.7.0
> openapi: virtnest version updated to v0.7.0

- docs/openapi/kant/v0.9.0.json
- docs/openapi/kant/v0.9.0.md
Upgrade kant openapi to v0.9.0
> Upgrade kant openapi to v0.9.0

- docs/openapi/skoala/v0.35.1.json
- docs/openapi/skoala/v0.35.1.md
openapi: skoala version updated to v0.35.1
> openapi: skoala version updated to v0.35.1

- docs/openapi/insight/v0.25.2.json
- docs/openapi/insight/v0.25.2.md
openapi: insight version updated to v0.25.2
> openapi: insight version updated to v0.25.2

- docs/openapi/virtnest/v0.7.1.json
- docs/openapi/virtnest/v0.7.1.md
openapi: virtnest version updated to v0.7.1
> openapi: virtnest version updated to v0.7.1

- docs/openapi/mcamel/minio/minio-v0.13.0.json
- docs/openapi/mcamel/minio/minio-v0.13.0.md
openapi: mcamel minio version updated to v0.13.0
> openapi: mcamel minio version updated to v0.13.0

- docs/openapi/mcamel/kafka/kafka-v0.13.0.json
- docs/openapi/mcamel/kafka/kafka-v0.13.0.md
openapi: mcamel kafka version updated to v0.13.0
> openapi: mcamel kafka version updated to v0.13.0

- docs/openapi/mcamel/elasticsearch/elasticsearch-v0.15.0.json
- docs/openapi/mcamel/elasticsearch/elasticsearch-v0.15.0.md
openapi: mcamel elasticsearch version updated to v0.15.0
> openapi: mcamel elasticsearch version updated to v0.15.0

- docs/openapi/mcamel/redis/redis-v0.16.0.json
- docs/openapi/mcamel/redis/redis-v0.16.0.md
openapi: mcamel redis version updated to v0.16.0
> openapi: mcamel redis version updated to v0.16.0

- docs/openapi/mcamel/mongodb/mongodb-v0.8.0.json
- docs/openapi/mcamel/mongodb/mongodb-v0.8.0.md
openapi: mcamel mongodb version updated to v0.8.0
> openapi: mcamel mongodb version updated to v0.8.0

- docs/openapi/mcamel/rocketmq-v0.5.0.json
- docs/openapi/mcamel/rocketmq-v0.5.0.md
openapi: mcamel rocketmq version updated to v0.5.0
> openapi: mcamel rocketmq version updated to v0.5.0

- docs/openapi/mcamel/postgresql/postgresql-v0.10.0.json
- docs/openapi/mcamel/postgresql/postgresql-v0.10.0.md
openapi: mcamel postgresql version updated to v0.10.0
> openapi: mcamel postgresql version updated to v0.10.0

- docs/openapi/mcamel/rabbitmq/rabbitmq-v0.18.0.json
- docs/openapi/mcamel/rabbitmq/rabbitmq-v0.18.0.md
openapi: mcamel rabbitmq version updated to v0.18.0
> openapi: mcamel rabbitmq version updated to v0.18.0

- docs/openapi/ghippo/v0.25.1.json
- docs/openapi/ghippo/v0.25.1.md
openapi: ghippo version updated to v0.25.1
> openapi: ghippo version updated to v0.25.1

- docs/openapi/ghippo/v0.25.0.json
- docs/openapi/ghippo/v0.25.0.md
openapi: ghippo version updated to v0.25.0
> openapi: ghippo version updated to v0.25.0

- docs/openapi/skoala/v0.35.2.json
- docs/openapi/skoala/v0.35.2.md
openapi: skoala version updated to v0.35.2
> openapi: skoala version updated to v0.35.2

- docs/openapi/kant/v0.10.0.json
- docs/openapi/kant/v0.10.0.md
> Add a new kant openapi version v0.10.0

- docs/openapi/skoala/v0.36.0.json
- docs/openapi/skoala/v0.36.0.md
openapi: skoala version updated to v0.36.0
> openapi: skoala version updated to v0.36.0

- docs/openapi/kangaroo/v0.17.0.json
- docs/openapi/kangaroo/v0.17.0.md
openapi: kangaroo version updated to v0.17.0
> openapi: kangaroo version updated to v0.17.0

- docs/openapi/spidernet/v0.14.0.json
- docs/openapi/spidernet/v0.14.0.md
openapi: spidernet version updated to v0.14.0
> openapi: spidernet version updated to v0.14.0

- docs/openapi/virtnest/v0.8.0.json
- docs/openapi/virtnest/v0.8.0.md
openapi: virtnest version updated to v0.8.0
> openapi: virtnest version updated to v0.8.0

- docs/openapi/skoala/v0.36.1.json
- docs/openapi/skoala/v0.36.1.md
openapi: skoala version updated to v0.36.1
> openapi: skoala version updated to v0.36.1

- docs/openapi/insight/v0.26.0.json
- docs/openapi/insight/v0.26.0.md
openapi: insight version updated to v0.26.0
> openapi: insight version updated to v0.26.0

- docs/openapi/mcamel/kafka/kafka-v0.14.0.json
- docs/openapi/mcamel/kafka/kafka-v0.14.0.md
openapi: mcamel kafka version updated to v0.14.0
> openapi: mcamel kafka version updated to v0.14.0

- docs/openapi/mcamel/redis/redis-v0.17.0.json
- docs/openapi/mcamel/redis/redis-v0.17.0.md
openapi: mcamel redis version updated to v0.17.0
> openapi: mcamel redis version updated to v0.17.0

- docs/openapi/mcamel/elasticsearch/elasticsearch-v0.16.0.json
- docs/openapi/mcamel/elasticsearch/elasticsearch-v0.16.0.md
openapi: mcamel elasticsearch version updated to v0.16.0
> openapi: mcamel elasticsearch version updated to v0.16.0

- docs/openapi/mcamel/mongodb/mongodb-v0.9.0.json
- docs/openapi/mcamel/mongodb/mongodb-v0.9.0.md
openapi: mcamel mongodb version updated to v0.9.0
> openapi: mcamel mongodb version updated to v0.9.0

- docs/openapi/mcamel/mysql/mysql-v0.17.1.json
- docs/openapi/mcamel/mysql/mysql-v0.17.1.md
openapi: mcamel mysql version updated to v0.17.1
> openapi: mcamel mysql version updated to v0.17.1

- docs/openapi/virtnest/v0.8.1.json
- docs/openapi/virtnest/v0.8.1.md
openapi: virtnest version updated to v0.8.1
> openapi: virtnest version updated to v0.8.1

- docs/openapi/ghippo/v0.26.0.json
- docs/openapi/ghippo/v0.26.0.md
openapi: ghippo version updated to v0.26.0
> openapi: ghippo version updated to v0.26.0

- docs/openapi/spidernet/v0.14.1.json
- docs/openapi/spidernet/v0.14.1.md
openapi: spidernet version updated to v0.14.1
> openapi: spidernet version updated to v0.14.1

- docs/openapi/kairship/v0.19.0.json
- docs/openapi/kairship/v0.19.0.md
openapi: kairship version updated to v0.19.0
> openapi: kairship version updated to v0.19.0

- docs/openapi/skoala/v0.37.0.json
- docs/openapi/skoala/v0.37.0.md
openapi: skoala version updated to v0.37.0
> openapi: skoala version updated to v0.37.0

- docs/openapi/kangaroo/v0.18.0.json
- docs/openapi/kangaroo/v0.18.0.md
openapi: kangaroo version updated to v0.18.0
> openapi: kangaroo version updated to v0.18.0

- docs/openapi/virtnest/v0.9.0.json
- docs/openapi/virtnest/v0.9.0.md
openapi: virtnest version updated to v0.9.0
> openapi: virtnest version updated to v0.9.0

- docs/openapi/mcamel/rocketmq-v0.7.0.json
- docs/openapi/mcamel/rocketmq-v0.7.0.md
openapi: mcamel rocketmq version updated to v0.7.0
> openapi: mcamel rocketmq version updated to v0.7.0

- docs/openapi/mcamel/mysql/mysql-v0.18.0.json
- docs/openapi/mcamel/mysql/mysql-v0.18.0.md
openapi: mcamel mysql version updated to v0.18.0
> openapi: mcamel mysql version updated to v0.18.0

- docs/openapi/mcamel/minio/minio-v0.15.0.json
- docs/openapi/mcamel/minio/minio-v0.15.0.md
openapi: mcamel minio version updated to v0.15.0
> openapi: mcamel minio version updated to v0.15.0

- docs/openapi/mcamel/elasticsearch/elasticsearch-v0.17.0.json
- docs/openapi/mcamel/elasticsearch/elasticsearch-v0.17.0.md
openapi: mcamel elasticsearch version updated to v0.17.0
> openapi: mcamel elasticsearch version updated to v0.17.0

- docs/openapi/mcamel/redis/redis-v0.18.0.json
- docs/openapi/mcamel/redis/redis-v0.18.0.md
openapi: mcamel redis version updated to v0.18.0
> openapi: mcamel redis version updated to v0.18.0

- docs/openapi/mcamel/rabbitmq/rabbitmq-v0.20.0.json
- docs/openapi/mcamel/rabbitmq/rabbitmq-v0.20.0.md
openapi: mcamel rabbitmq version updated to v0.20.0
> openapi: mcamel rabbitmq version updated to v0.20.0

- docs/openapi/mcamel/kafka/kafka-v0.15.0.json
- docs/openapi/mcamel/kafka/kafka-v0.15.0.md
openapi: mcamel kafka version updated to v0.15.0
> openapi: mcamel kafka version updated to v0.15.0

- docs/openapi/ghippo/v0.27.0.json
- docs/openapi/ghippo/v0.27.0.md
openapi: ghippo version updated to v0.27.0
> openapi: ghippo version updated to v0.27.0

- docs/openapi/skoala/v0.37.1.json
- docs/openapi/skoala/v0.37.1.md
openapi: skoala version updated to v0.37.1
> openapi: skoala version updated to v0.37.1

- docs/openapi/insight/v0.27.1.md
openapi: insight version updated to v0.27.1
> openapi: insight version updated to v0.27.1

- docs/openapi/insight/v0.27.0.md
openapi: insight version updated to v0.27.0
> openapi: insight version updated to v0.27.0

- docs/openapi/skoala/v0.38.1.json
- docs/openapi/skoala/v0.38.1.md
openapi: skoala version updated to v0.38.1
> openapi: skoala version updated to v0.38.1

- docs/openapi/kairship/v0.20.0.json
- docs/openapi/kairship/v0.20.0.md
openapi: kairship version updated to v0.20.0
> openapi: kairship version updated to v0.20.0

- docs/openapi/kairship/v0.20.1.json
- docs/openapi/kairship/v0.20.1.md
openapi: kairship version updated to v0.20.1
> openapi: kairship version updated to v0.20.1

- docs/openapi/insight/v0.28.0.json
- docs/openapi/insight/v0.28.0.md
openapi: insight version updated to v0.28.0
> openapi: insight version updated to v0.28.0

- docs/openapi/ghippo/v0.28.0.json
- docs/openapi/ghippo/v0.28.0.md
openapi: ghippo version updated to v0.28.0
> openapi: ghippo version updated to v0.28.0

- docs/openapi/mcamel/redis/redis-v0.19.0.json
- docs/openapi/mcamel/redis/redis-v0.19.0.md
openapi: mcamel redis version updated to v0.19.0
> openapi: mcamel redis version updated to v0.19.0

- docs/openapi/mcamel/rabbitmq/rabbitmq-v0.21.0.json
- docs/openapi/mcamel/rabbitmq/rabbitmq-v0.21.0.md
openapi: mcamel rabbitmq version updated to v0.21.0
> openapi: mcamel rabbitmq version updated to v0.21.0

- docs/openapi/mcamel/elasticsearch/elasticsearch-v0.18.0.json
- docs/openapi/mcamel/elasticsearch/elasticsearch-v0.18.0.md
openapi: mcamel elasticsearch version updated to v0.18.0
> openapi: mcamel elasticsearch version updated to v0.18.0

- docs/openapi/mcamel/rocketmq-v0.8.0.json
- docs/openapi/mcamel/rocketmq-v0.8.0.md
openapi: mcamel rocketmq version updated to v0.8.0
> openapi: mcamel rocketmq version updated to v0.8.0

- docs/openapi/mcamel/kafka/kafka-v0.16.0.json
- docs/openapi/mcamel/kafka/kafka-v0.16.0.md
openapi: mcamel kafka version updated to v0.16.0
> openapi: mcamel kafka version updated to v0.16.0

- docs/openapi/mcamel/mongodb/mongodb-v0.11.0.json
- docs/openapi/mcamel/mongodb/mongodb-v0.11.0.md
openapi: mcamel mongodb version updated to v0.11.0
> openapi: mcamel mongodb version updated to v0.11.0

- docs/openapi/mcamel/mysql/mysql-v0.19.0.json
- docs/openapi/mcamel/mysql/mysql-v0.19.0.md
openapi: mcamel mysql version updated to v0.19.0
> openapi: mcamel mysql version updated to v0.19.0

- docs/openapi/mcamel/minio/minio-v0.16.0.json
- docs/openapi/mcamel/minio/minio-v0.16.0.md
openapi: mcamel minio version updated to v0.16.0
> openapi: mcamel minio version updated to v0.16.0

- docs/openapi/mcamel/postgresql/postgresql-v0.13.0.json
- docs/openapi/mcamel/postgresql/postgresql-v0.13.0.md
openapi: mcamel postgresql version updated to v0.13.0
> openapi: mcamel postgresql version updated to v0.13.0

- docs/openapi/skoala/v0.38.2.json
- docs/openapi/skoala/v0.38.2.md
openapi: skoala version updated to v0.38.2
> openapi: skoala version updated to v0.38.2

- docs/openapi/index.md
- openapi-nav.yml
> update nav and index

- docs/openapi/kant/v0.13.0.json
- docs/openapi/kant/v0.13.0.md
kant version updated to v0.13.0
> kant version updated to v0.13.0

- docs/openapi/kairship/v0.21.0.json
- docs/openapi/kairship/v0.21.0.md
openapi: kairship version updated to v0.21.0
> openapi: kairship version updated to v0.21.0

- docs/openapi/mcamel/rabbitmq/rabbitmq-v0.22.0.json
- docs/openapi/mcamel/rabbitmq/rabbitmq-v0.22.0.md
openapi: mcamel rabbitmq version updated to v0.22.0
> openapi: mcamel rabbitmq version updated to v0.22.0

- docs/openapi/mcamel/kafka/kafka-v0.17.0.json
- docs/openapi/mcamel/kafka/kafka-v0.17.0.md
openapi: mcamel kafka version updated to v0.17.0
> openapi: mcamel kafka version updated to v0.17.0

- docs/openapi/mcamel/mongodb/mongodb-v0.12.0.json
- docs/openapi/mcamel/mongodb/mongodb-v0.12.0.md
openapi: mcamel mongodb version updated to v0.12.0
> openapi: mcamel mongodb version updated to v0.12.0

- docs/openapi/mcamel/postgresql/postgresql-v0.14.0.json
- docs/openapi/mcamel/postgresql/postgresql-v0.14.0.md
openapi: mcamel postgresql version updated to v0.14.0
> openapi: mcamel postgresql version updated to v0.14.0

- docs/openapi/spidernet/v0.15.1.json
- docs/openapi/spidernet/v0.15.1.md
openapi: spidernet version updated to v0.15.1
> openapi: spidernet version updated to v0.15.1

- docs/openapi/kant/v0.14.0.json
- docs/openapi/kant/v0.14.0.md
openapi: kant version updated to v0.14.0
> openapi: kant version updated to v0.14.0

- docs/openapi/kangaroo/v0.21.0.json
- docs/openapi/kangaroo/v0.21.0.md
openapi: kangaroo version updated to v0.21.0
> openapi: kangaroo version updated to v0.21.0

- docs/openapi/kairship/v0.22.0.json
- docs/openapi/kairship/v0.22.0.md
openapi: kairship version updated to v0.22.0
> openapi: kairship version updated to v0.22.0

- docs/openapi/ghippo/v0.30.0.json
- docs/openapi/ghippo/v0.30.0.md
openapi: ghippo version updated to v0.30.0
> openapi: ghippo version updated to v0.30.0

- docs/openapi/mcamel/elasticsearch/elasticsearch-v0.20.0.json
- docs/openapi/mcamel/elasticsearch/elasticsearch-v0.20.0.md
openapi: mcamel elasticsearch version updated to v0.20.0
> openapi: mcamel elasticsearch version updated to v0.20.0

- docs/openapi/mcamel/mongodb/mongodb-v0.13.0.json
- docs/openapi/mcamel/mongodb/mongodb-v0.13.0.md
openapi: mcamel mongodb version updated to v0.13.0
> openapi: mcamel mongodb version updated to v0.13.0

- docs/openapi/mcamel/minio/minio-v0.18.0.json
- docs/openapi/mcamel/minio/minio-v0.18.0.md
openapi: mcamel minio version updated to v0.18.0
> openapi: mcamel minio version updated to v0.18.0

- docs/openapi/mcamel/kafka/kafka-v0.18.0.json
- docs/openapi/mcamel/kafka/kafka-v0.18.0.md
openapi: mcamel kafka version updated to v0.18.0
> openapi: mcamel kafka version updated to v0.18.0

- docs/openapi/mcamel/mysql/mysql-v0.21.0.json
- docs/openapi/mcamel/mysql/mysql-v0.21.0.md
openapi: mcamel mysql version updated to v0.21.0
> openapi: mcamel mysql version updated to v0.21.0

- docs/openapi/mcamel/rabbitmq/rabbitmq-v0.23.0.json
- docs/openapi/mcamel/rabbitmq/rabbitmq-v0.23.0.md
openapi: mcamel rabbitmq version updated to v0.23.0
> openapi: mcamel rabbitmq version updated to v0.23.0

- docs/openapi/mcamel/rocketmq-v0.10.0.json
- docs/openapi/mcamel/rocketmq-v0.10.0.md
openapi: mcamel rocketmq version updated to v0.10.0
> openapi: mcamel rocketmq version updated to v0.10.0

- docs/openapi/mcamel/redis/redis-v0.21.0.json
- docs/openapi/mcamel/redis/redis-v0.21.0.md
openapi: mcamel redis version updated to v0.21.0
> openapi: mcamel redis version updated to v0.21.0

- docs/openapi/mcamel/mongodb/mongodb-v0.13.1.json
- docs/openapi/mcamel/mongodb/mongodb-v0.13.1.md
openapi: mcamel mongodb version updated to v0.13.1
> openapi: mcamel mongodb version updated to v0.13.1

- docs/openapi/mcamel/postgresql/postgresql-v0.15.0.json
- docs/openapi/mcamel/postgresql/postgresql-v0.15.0.md
openapi: mcamel postgresql version updated to v0.15.0
> openapi: mcamel postgresql version updated to v0.15.0

- docs/openapi/mcamel/minio/minio-v0.18.1.json
- docs/openapi/mcamel/minio/minio-v0.18.1.md
openapi: mcamel minio version updated to v0.18.1
> openapi: mcamel minio version updated to v0.18.1

- docs/openapi/kant/v0.15.0.json
- docs/openapi/kant/v0.15.0.md
openapi: kant version updated to v0.15.0
> openapi: kant version updated to v0.15.0

- docs/openapi/spidernet/v0.16.0.json
- docs/openapi/spidernet/v0.16.0.md
openapi: spidernet version updated to v0.16.0
> openapi: spidernet version updated to v0.16.0

- docs/openapi/kangaroo/v0.22.0-rc1.json
- docs/openapi/kangaroo/v0.22.0-rc1.md
openapi: kangaroo version updated to v0.22.0-rc1
> openapi: kangaroo version updated to v0.22.0-rc1

- docs/openapi/mcamel/elasticsearch/elasticsearch-v0.21.1.json
- docs/openapi/mcamel/elasticsearch/elasticsearch-v0.21.1.md
openapi: mcamel elasticsearch version updated to v0.21.1
> openapi: mcamel elasticsearch version updated to v0.21.1

- docs/openapi/mcamel/kafka/kafka-v0.19.0.json
- docs/openapi/mcamel/kafka/kafka-v0.19.0.md
openapi: mcamel kafka version updated to v0.19.0
> openapi: mcamel kafka version updated to v0.19.0

- docs/openapi/mcamel/mysql/mysql-v0.22.0.json
- docs/openapi/mcamel/mysql/mysql-v0.22.0.md
openapi: mcamel mysql version updated to v0.22.0
> openapi: mcamel mysql version updated to v0.22.0

- docs/openapi/mcamel/redis/redis-v0.22.0.json
- docs/openapi/mcamel/redis/redis-v0.22.0.md
openapi: mcamel redis version updated to v0.22.0
> openapi: mcamel redis version updated to v0.22.0

- docs/openapi/mcamel/rabbitmq/rabbitmq-v0.24.0.json
- docs/openapi/mcamel/rabbitmq/rabbitmq-v0.24.0.md
openapi: mcamel rabbitmq version updated to v0.24.0
> openapi: mcamel rabbitmq version updated to v0.24.0

- docs/openapi/mcamel/postgresql/postgresql-v0.16.0.json
- docs/openapi/mcamel/postgresql/postgresql-v0.16.0.md
openapi: mcamel postgresql version updated to v0.16.0
> openapi: mcamel postgresql version updated to v0.16.0

- docs/openapi/mcamel/elasticsearch/elasticsearch-v0.21.0.json
- docs/openapi/mcamel/elasticsearch/elasticsearch-v0.21.0.md
openapi: mcamel elasticsearch version updated to v0.21.0
> openapi: mcamel elasticsearch version updated to v0.21.0

- docs/openapi/mcamel/mongodb/mongodb-v0.14.0.json
- docs/openapi/mcamel/mongodb/mongodb-v0.14.0.md
openapi: mcamel mongodb version updated to v0.14.0
> openapi: mcamel mongodb version updated to v0.14.0

- docs/openapi/mcamel/rocketmq-v0.11.0.json
- docs/openapi/mcamel/rocketmq-v0.11.0.md
openapi: mcamel rocketmq version updated to v0.11.0
> openapi: mcamel rocketmq version updated to v0.11.0

- docs/openapi/mcamel/minio/minio-v0.19.0.json
- docs/openapi/mcamel/minio/minio-v0.19.0.md
openapi: mcamel minio version updated to v0.19.0
> openapi: mcamel minio version updated to v0.19.0

- docs/openapi/ghippo/v0.31.0.json
- docs/openapi/ghippo/v0.31.0.md
openapi: ghippo version updated to v0.31.0
> openapi: ghippo version updated to v0.31.0

- docs/openapi/virtnest/v0.13.0.json
- docs/openapi/virtnest/v0.13.0.md
openapi: virtnest version updated to v0.13.0
> openapi: virtnest version updated to v0.13.0

- docs/openapi/kairship/v0.23.0.json
- docs/openapi/kairship/v0.23.0.md
openapi: kairship version updated to v0.23.0
> openapi: kairship version updated to v0.23.0

- docs/openapi/kangaroo/v0.22.0.json
- docs/openapi/kangaroo/v0.22.0.md
openapi: kangaroo version updated to v0.22.0
> openapi: kangaroo version updated to v0.22.0

- docs/openapi/kant/v0.16.1.json
- docs/openapi/kant/v0.16.1.md
openapi: kant version updated to v0.16.1
> openapi: kant version updated to v0.16.1

- docs/openapi/mcamel/rabbitmq/rabbitmq-v0.25.0.json
- docs/openapi/mcamel/rabbitmq/rabbitmq-v0.25.0.md
openapi: mcamel rabbitmq version updated to v0.25.0
> openapi: mcamel rabbitmq version updated to v0.25.0

- docs/openapi/mcamel/minio/minio-v0.20.0.json
- docs/openapi/mcamel/minio/minio-v0.20.0.md
openapi: mcamel minio version updated to v0.20.0
> openapi: mcamel minio version updated to v0.20.0

- docs/openapi/mcamel/redis/redis-v0.23.0.json
- docs/openapi/mcamel/redis/redis-v0.23.0.md
openapi: mcamel redis version updated to v0.23.0
> openapi: mcamel redis version updated to v0.23.0

- docs/openapi/mcamel/postgresql/postgresql-v0.17.0.json
- docs/openapi/mcamel/postgresql/postgresql-v0.17.0.md
openapi: mcamel postgresql version updated to v0.17.0
> openapi: mcamel postgresql version updated to v0.17.0

- docs/openapi/mcamel/rocketmq-v0.12.0.json
- docs/openapi/mcamel/rocketmq-v0.12.0.md
openapi: mcamel rocketmq version updated to v0.12.0
> openapi: mcamel rocketmq version updated to v0.12.0

- docs/openapi/mcamel/mongodb/mongodb-v0.15.0.json
- docs/openapi/mcamel/mongodb/mongodb-v0.15.0.md
openapi: mcamel mongodb version updated to v0.15.0
> openapi: mcamel mongodb version updated to v0.15.0

- docs/openapi/mcamel/mysql/mysql-v0.23.0.json
- docs/openapi/mcamel/mysql/mysql-v0.23.0.md
openapi: mcamel mysql version updated to v0.23.0
> openapi: mcamel mysql version updated to v0.23.0

- docs/openapi/spidernet/v0.16.1.json
- docs/openapi/spidernet/v0.16.1.md
openapi: spidernet version updated to v0.16.1
> openapi: spidernet version updated to v0.16.1

- docs/openapi/insight/v0.31.3.json
- docs/openapi/insight/v0.31.3.md
openapi: insight version updated to v0.31.3
> openapi: insight version updated to v0.31.3

- docs/openapi/spidernet/v0.16.2.json
- docs/openapi/spidernet/v0.16.2.md
openapi: spidernet version updated to v0.16.2
> openapi: spidernet version updated to v0.16.2

- docs/openapi/virtnest/v0.15.0.json
- docs/openapi/virtnest/v0.15.0.md
openapi: virtnest version updated to v0.15.0
> openapi: virtnest version updated to v0.15.0

- docs/openapi/mcamel/rabbitmq/rabbitmq-v0.26.0.json
- docs/openapi/mcamel/rabbitmq/rabbitmq-v0.26.0.md
openapi: mcamel rabbitmq version updated to v0.26.0
> openapi: mcamel rabbitmq version updated to v0.26.0

- docs/openapi/mcamel/mongodb/mongodb-v0.16.0.json
- docs/openapi/mcamel/mongodb/mongodb-v0.16.0.md
openapi: mcamel mongodb version updated to v0.16.0
> openapi: mcamel mongodb version updated to v0.16.0

- docs/openapi/mcamel/minio/minio-v0.21.0.json
- docs/openapi/mcamel/minio/minio-v0.21.0.md
openapi: mcamel minio version updated to v0.21.0
> openapi: mcamel minio version updated to v0.21.0

- docs/openapi/mcamel/kafka/kafka-v0.21.0.json
- docs/openapi/mcamel/kafka/kafka-v0.21.0.md
openapi: mcamel kafka version updated to v0.21.0
> openapi: mcamel kafka version updated to v0.21.0

- docs/openapi/mcamel/rocketmq-v0.13.0.json
- docs/openapi/mcamel/rocketmq-v0.13.0.md
openapi: mcamel rocketmq version updated to v0.13.0
> openapi: mcamel rocketmq version updated to v0.13.0

- docs/openapi/mcamel/postgresql/postgresql-v0.18.0.json
- docs/openapi/mcamel/postgresql/postgresql-v0.18.0.md
openapi: mcamel postgresql version updated to v0.18.0
> openapi: mcamel postgresql version updated to v0.18.0

- docs/openapi/mcamel/elasticsearch/elasticsearch-v0.23.0.json
- docs/openapi/mcamel/elasticsearch/elasticsearch-v0.23.0.md
openapi: mcamel elasticsearch version updated to v0.23.0
> openapi: mcamel elasticsearch version updated to v0.23.0

- docs/openapi/mcamel/mysql/mysql-v0.24.0.json
- docs/openapi/mcamel/mysql/mysql-v0.24.0.md
openapi: mcamel mysql version updated to v0.24.0
> openapi: mcamel mysql version updated to v0.24.0

- docs/openapi/insight/v0.33.1.json
- docs/openapi/insight/v0.33.1.md
openapi: insight version updated to v0.33.1
> openapi: insight version updated to v0.33.1

- docs/openapi/insight/v0.34.0.json
- docs/openapi/insight/v0.34.0.md
openapi: insight version updated to v0.34.0
> openapi: insight version updated to v0.34.0

- docs/openapi/mcamel/redis/redis-v0.25.0.json
- docs/openapi/mcamel/redis/redis-v0.25.0.md
openapi: mcamel redis version updated to v0.25.0
> openapi: mcamel redis version updated to v0.25.0

- docs/openapi/mcamel/mysql/mysql-v0.25.0.json
- docs/openapi/mcamel/mysql/mysql-v0.25.0.md
openapi: mcamel mysql version updated to v0.25.0
> openapi: mcamel mysql version updated to v0.25.0

- docs/openapi/insight/v0.34.1.json
- docs/openapi/insight/v0.34.1.md
openapi: insight version updated to v0.34.1
> openapi: insight version updated to v0.34.1

- docs/openapi/ghippo/v0.33.0.json
- docs/openapi/ghippo/v0.33.0.md
openapi: ghippo version updated to v0.33.0
> openapi: ghippo version updated to v0.33.0

- docs/openapi/mcamel/rabbitmq/rabbitmq-v0.27.0.json
- docs/openapi/mcamel/rabbitmq/rabbitmq-v0.27.0.md
openapi: mcamel rabbitmq version updated to v0.27.0
> openapi: mcamel rabbitmq version updated to v0.27.0

- docs/openapi/mcamel/kafka/kafka-v0.22.0.json
- docs/openapi/mcamel/kafka/kafka-v0.22.0.md
openapi: mcamel kafka version updated to v0.22.0
> openapi: mcamel kafka version updated to v0.22.0

- docs/openapi/mcamel/redis/redis-v0.26.0.json
- docs/openapi/mcamel/redis/redis-v0.26.0.md
openapi: mcamel redis version updated to v0.26.0
> openapi: mcamel redis version updated to v0.26.0

- docs/openapi/ghippo/v0.34.0.json
- docs/openapi/ghippo/v0.34.0.md
openapi: ghippo version updated to v0.34.0
> openapi: ghippo version updated to v0.34.0

- docs/openapi/index.md
- docs/openapi/midware.md
remove the oldest page from index
> fix index layout

- docs/openapi/ghippo/v0.35.0.json
- docs/openapi/ghippo/v0.35.0.md
openapi: ghippo version updated to v0.35.0
> openapi: ghippo version updated to v0.35.0

- docs/openapi/mcamel/mysql/mysql-v0.26.0.json
- docs/openapi/mcamel/mysql/mysql-v0.26.0.md
openapi: mcamel mysql version updated to v0.26.0
> openapi: mcamel mysql version updated to v0.26.0

- docs/openapi/virtnest/v0.16.0.json
- docs/openapi/virtnest/v0.16.0.md
openapi: virtnest version updated to v0.16.0
> openapi: virtnest version updated to v0.16.0

- docs/openapi/mcamel/elasticsearch/elasticsearch-v0.24.0.json
- docs/openapi/mcamel/elasticsearch/elasticsearch-v0.24.0.md
openapi: mcamel elasticsearch version updated to v0.24.0
> openapi: mcamel elasticsearch version updated to v0.24.0

- docs/openapi/insight/v0.34.2.json
- docs/openapi/insight/v0.34.2.md
openapi: insight version updated to v0.34.2
> openapi: insight version updated to v0.34.2

- docs/openapi/insight/v0.35.0.json
- docs/openapi/insight/v0.35.0.md
openapi: insight version updated to v0.35.0
> openapi: insight version updated to v0.35.0

- docs/openapi/insight/v0.35.1.json
- docs/openapi/insight/v0.35.1.md
openapi: insight version updated to v0.35.1
> openapi: insight version updated to v0.35.1

- docs/openapi/ghippo/v0.35.1.json
- docs/openapi/ghippo/v0.35.1.md
openapi: ghippo version updated to v0.35.1
> openapi: ghippo version updated to v0.35.1

- docs/openapi/virtnest/v0.17.0.json
- docs/openapi/virtnest/v0.17.0.md
openapi: virtnest version updated to v0.17.0
> openapi: virtnest version updated to v0.17.0

- docs/openapi/spidernet/v0.16.3.json
- docs/openapi/spidernet/v0.16.3.md
openapi: spidernet version updated to v0.16.3
> openapi: spidernet version updated to v0.16.3

- docs/openapi/mcamel/postgresql/postgresql-v0.18.2.json
- docs/openapi/mcamel/postgresql/postgresql-v0.18.2.md
openapi: mcamel postgresql version updated to v0.18.2
> openapi: mcamel postgresql version updated to v0.18.2

- docs/openapi/mcamel/mysql/mysql-v0.26.2.json
- docs/openapi/mcamel/mysql/mysql-v0.26.2.md
openapi: mcamel mysql version updated to v0.26.2
> openapi: mcamel mysql version updated to v0.26.2

- docs/openapi/mcamel/mongodb/mongodb-v0.16.2.json
- docs/openapi/mcamel/mongodb/mongodb-v0.16.2.md
openapi: mcamel mongodb version updated to v0.16.2
> openapi: mcamel mongodb version updated to v0.16.2

- docs/openapi/mcamel/rabbitmq/rabbitmq-v0.27.1.json
- docs/openapi/mcamel/rabbitmq/rabbitmq-v0.27.1.md
openapi: mcamel rabbitmq version updated to v0.27.1
> openapi: mcamel rabbitmq version updated to v0.27.1

- docs/openapi/mcamel/minio/minio-v0.21.1.json
- docs/openapi/mcamel/minio/minio-v0.21.1.md
openapi: mcamel minio version updated to v0.21.1
> openapi: mcamel minio version updated to v0.21.1

- docs/openapi/mcamel/mongodb/mongodb-v0.16.1.json
- docs/openapi/mcamel/mongodb/mongodb-v0.16.1.md
openapi: mcamel mongodb version updated to v0.16.1
> openapi: mcamel mongodb version updated to v0.16.1

- docs/openapi/mcamel/postgresql/postgresql-v0.18.1.json
- docs/openapi/mcamel/postgresql/postgresql-v0.18.1.md
openapi: mcamel postgresql version updated to v0.18.1
> openapi: mcamel postgresql version updated to v0.18.1

- docs/openapi/mcamel/redis/redis-v0.27.1.json
- docs/openapi/mcamel/redis/redis-v0.27.1.md
openapi: mcamel redis version updated to v0.27.1
> openapi: mcamel redis version updated to v0.27.1

- docs/openapi/mcamel/mysql/mysql-v0.26.1.json
- docs/openapi/mcamel/mysql/mysql-v0.26.1.md
openapi: mcamel mysql version updated to v0.26.1
> openapi: mcamel mysql version updated to v0.26.1

- docs/openapi/mcamel/elasticsearch/elasticsearch-v0.24.1.json
- docs/openapi/mcamel/elasticsearch/elasticsearch-v0.24.1.md
openapi: mcamel elasticsearch version updated to v0.24.1
> openapi: mcamel elasticsearch version updated to v0.24.1

- docs/openapi/mcamel/rabbitmq/rabbitmq-v0.27.2.json
- docs/openapi/mcamel/rabbitmq/rabbitmq-v0.27.2.md
openapi: mcamel rabbitmq version updated to v0.27.2
> openapi: mcamel rabbitmq version updated to v0.27.2

- docs/openapi/mcamel/kafka/kafka-v0.24.0.json
- docs/openapi/mcamel/kafka/kafka-v0.24.0.md
openapi: mcamel kafka version updated to v0.24.0
> openapi: mcamel kafka version updated to v0.24.0

- docs/openapi/mcamel/postgresql/postgresql-v0.18.3.json
- docs/openapi/mcamel/postgresql/postgresql-v0.18.3.md
openapi: mcamel postgresql version updated to v0.18.3
> openapi: mcamel postgresql version updated to v0.18.3

- docs/openapi/mcamel/rocketmq-v0.15.0.json
- docs/openapi/mcamel/rocketmq-v0.15.0.md
openapi: mcamel rocketmq version updated to v0.15.0
> openapi: mcamel rocketmq version updated to v0.15.0

- docs/openapi/insight/v0.36.0.json
- docs/openapi/insight/v0.36.0.md
openapi: insight version updated to v0.36.0
> openapi: insight version updated to v0.36.0

- docs/openapi/insight/v0.36.1.json
- docs/openapi/insight/v0.36.1.md
openapi: insight version updated to v0.36.1
> openapi: insight version updated to v0.36.1

- docs/openapi/ghippo/v0.36.0.json
- docs/openapi/ghippo/v0.36.0.md
openapi: ghippo version updated to v0.36.0
> openapi: ghippo version updated to v0.36.0

- docs/openapi/ghippo/v0.37.0.json
- docs/openapi/ghippo/v0.37.0.md
openapi: ghippo version updated to v0.37.0
> openapi: ghippo version updated to v0.37.0

- docs/openapi/mcamel/elasticsearch/elasticsearch-v0.24.2.json
- docs/openapi/mcamel/elasticsearch/elasticsearch-v0.24.2.md
openapi: mcamel elasticsearch version updated to v0.24.2
> openapi: mcamel elasticsearch version updated to v0.24.2

- docs/openapi/mcamel/kafka/kafka-v0.24.1.json
- docs/openapi/mcamel/kafka/kafka-v0.24.1.md
openapi: mcamel kafka version updated to v0.24.1
> openapi: mcamel kafka version updated to v0.24.1

- docs/openapi/mcamel/postgresql/postgresql-v0.18.4.json
- docs/openapi/mcamel/postgresql/postgresql-v0.18.4.md
openapi: mcamel postgresql version updated to v0.18.4
> openapi: mcamel postgresql version updated to v0.18.4

- docs/openapi/insight/v0.31.7.json
- docs/openapi/insight/v0.31.7.md
openapi: insight version updated to v0.31.7
> openapi: insight version updated to v0.31.7

- docs/openapi/mcamel/mysql/mysql-v0.26.3.json
- docs/openapi/mcamel/mysql/mysql-v0.26.3.md
openapi: mcamel mysql version updated to v0.26.3
> openapi: mcamel mysql version updated to v0.26.3

- docs/openapi/virtnest/v0.18.0.json
- docs/openapi/virtnest/v0.18.0.md
openapi: virtnest version updated to v0.18.0
> openapi: virtnest version updated to v0.18.0

- docs/openapi/virtnest/v0.18.1.json
- docs/openapi/virtnest/v0.18.1.md
openapi: virtnest version updated to v0.18.1
> openapi: virtnest version updated to v0.18.1

- docs/openapi/mcamel/kafka/kafka-v0.24.2.json
- docs/openapi/mcamel/kafka/kafka-v0.24.2.md
openapi: mcamel kafka version updated to v0.24.2
> openapi: mcamel kafka version updated to v0.24.2

- docs/openapi/insight/v0.37.0.json
- docs/openapi/insight/v0.37.0.md
openapi: insight version updated to v0.37.0
> openapi: insight version updated to v0.37.0

- docs/openapi/insight/v0.37.1.json
- docs/openapi/insight/v0.37.1.md
openapi: insight version updated to v0.37.1
> openapi: insight version updated to v0.37.1

- docs/openapi/insight/v0.37.2.json
- docs/openapi/insight/v0.37.2.md
openapi: insight version updated to v0.37.2
> openapi: insight version updated to v0.37.2

- docs/openapi/zestu/v0.9.0.json
- docs/openapi/zestu/v0.9.0.md
openapi: zestu version updated to v0.9.0
> openapi: zestu version updated to v0.9.0

- docs/openapi/ghippo/v0.40.0.json
- docs/openapi/ghippo/v0.40.0.md
openapi: ghippo version updated to v0.40.0
> openapi: ghippo version updated to v0.40.0

- docs/openapi/mcamel/postgresql/postgresql-v0.19.0.json
- docs/openapi/mcamel/postgresql/postgresql-v0.19.0.md
openapi: mcamel postgresql version updated to v0.19.0
> openapi: mcamel postgresql version updated to v0.19.0

- docs/openapi/mcamel/kafka/kafka-v0.25.0.json
- docs/openapi/mcamel/kafka/kafka-v0.25.0.md
openapi: mcamel kafka version updated to v0.25.0
> openapi: mcamel kafka version updated to v0.25.0

- docs/openapi/mcamel/elasticsearch/elasticsearch-v0.25.0.json
- docs/openapi/mcamel/elasticsearch/elasticsearch-v0.25.0.md
openapi: mcamel elasticsearch version updated to v0.25.0
> openapi: mcamel elasticsearch version updated to v0.25.0

- docs/openapi/mcamel/redis/redis-v0.28.0.json
- docs/openapi/mcamel/redis/redis-v0.28.0.md
openapi: mcamel redis version updated to v0.28.0
> openapi: mcamel redis version updated to v0.28.0

- docs/openapi/mcamel/mysql/mysql-v0.27.0.json
- docs/openapi/mcamel/mysql/mysql-v0.27.0.md
openapi: mcamel mysql version updated to v0.27.0
> openapi: mcamel mysql version updated to v0.27.0

- docs/openapi/insight/v0.38.0.json
- docs/openapi/insight/v0.38.0.md
openapi: insight version updated to v0.38.0
> openapi: insight version updated to v0.38.0

- docs/openapi/mcamel/elasticsearch/elasticsearch-v0.25.1.json
- docs/openapi/mcamel/elasticsearch/elasticsearch-v0.25.1.md
openapi: mcamel elasticsearch version updated to v0.25.1
> openapi: mcamel elasticsearch version updated to v0.25.1

- docs/openapi/mcamel/mysql/mysql-v0.27.1.json
- docs/openapi/mcamel/mysql/mysql-v0.27.1.md
openapi: mcamel mysql version updated to v0.27.1
> openapi: mcamel mysql version updated to v0.27.1
